
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class PlaysSelectionWidget
	{
		private global::Gtk.Notebook notebook;
		
		private global::LongoMatch.Gui.Component.EventsListWidget eventslistwidget;
		
		private global::Gtk.Label label1;
		
		private global::LongoMatch.Gui.Component.PlayListWidget playlistwidget;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.VBox filtersvbox;
		
		private global::Gtk.Notebook filtersnotebook;
		
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.PlaysSelectionWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.PlaysSelectionWidget";
			// Container child LongoMatch.Gui.Component.PlaysSelectionWidget.Gtk.Container+ContainerChild
			this.notebook = new global::Gtk.Notebook ();
			this.notebook.CanFocus = true;
			this.notebook.Name = "notebook";
			this.notebook.CurrentPage = 0;
			this.notebook.TabPos = ((global::Gtk.PositionType)(0));
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.eventslistwidget = new global::LongoMatch.Gui.Component.EventsListWidget ();
			this.eventslistwidget.Events = ((global::Gdk.EventMask)(256));
			this.eventslistwidget.Name = "eventslistwidget";
			this.notebook.Add (this.eventslistwidget);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::LongoMatch.Core.Catalog.GetString ("  Events   ");
			this.label1.Justify = ((global::Gtk.Justification)(2));
			this.label1.Angle = 90;
			this.notebook.SetTabLabel (this.eventslistwidget, this.label1);
			this.label1.ShowAll ();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.playlistwidget = new global::LongoMatch.Gui.Component.PlayListWidget ();
			this.playlistwidget.WidthRequest = 100;
			this.playlistwidget.Events = ((global::Gdk.EventMask)(256));
			this.playlistwidget.Name = "playlistwidget";
			this.notebook.Add (this.playlistwidget);
			global::Gtk.Notebook.NotebookChild w2 = ((global::Gtk.Notebook.NotebookChild)(this.notebook [this.playlistwidget]));
			w2.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::LongoMatch.Core.Catalog.GetString ("Playlists");
			this.label3.Angle = 90;
			this.notebook.SetTabLabel (this.playlistwidget, this.label3);
			this.label3.ShowAll ();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.filtersvbox = new global::Gtk.VBox ();
			this.filtersvbox.Name = "filtersvbox";
			this.filtersvbox.Spacing = 6;
			// Container child filtersvbox.Gtk.Box+BoxChild
			this.filtersnotebook = new global::Gtk.Notebook ();
			this.filtersnotebook.CanFocus = true;
			this.filtersnotebook.Name = "filtersnotebook";
			this.filtersnotebook.CurrentPage = 1;
			this.filtersnotebook.TabPos = ((global::Gtk.PositionType)(3));
			this.filtersvbox.Add (this.filtersnotebook);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.filtersvbox [this.filtersnotebook]));
			w3.Position = 0;
			this.notebook.Add (this.filtersvbox);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook [this.filtersvbox]));
			w4.Position = 2;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::LongoMatch.Core.Catalog.GetString ("  Filters  ");
			this.label2.Angle = 90;
			this.notebook.SetTabLabel (this.filtersvbox, this.label2);
			this.label2.ShowAll ();
			this.Add (this.notebook);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
