
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class AnalysisTemplateEditor
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::LongoMatch.Gui.Component.ButtonsWidget buttonswidget;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Frame frame8;
		private global::Gtk.Alignment GtkAlignment13;
		private global::Gtk.HBox hbox6;
		private global::Gtk.EventBox fieldeventbox;
		private global::Gtk.Image fieldimage;
		private global::Gtk.Button resetfieldbutton;
		private global::Gtk.Label GtkLabel17;
		private global::Gtk.Frame frame9;
		private global::Gtk.Alignment GtkAlignment15;
		private global::Gtk.HBox hbox7;
		private global::Gtk.EventBox hfieldeventbox;
		private global::Gtk.Image hfieldimage;
		private global::Gtk.Button resethfieldbutton;
		private global::Gtk.Label GtkLabel20;
		private global::Gtk.Frame frame10;
		private global::Gtk.Alignment GtkAlignment17;
		private global::Gtk.HBox hbox8;
		private global::Gtk.EventBox goaleventbox;
		private global::Gtk.Image goalimage;
		private global::Gtk.Button resetfgoalbutton;
		private global::Gtk.Label GtkLabel22;
		private global::LongoMatch.Gui.Component.CategoryProperties categoryproperties;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button savebutton;
		private global::Gtk.Button newbutton;
		private global::Gtk.Button deletebutton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.AnalysisTemplateEditor
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.AnalysisTemplateEditor";
			// Container child LongoMatch.Gui.Component.AnalysisTemplateEditor.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonswidget = new global::LongoMatch.Gui.Component.ButtonsWidget ();
			this.buttonswidget.Events = ((global::Gdk.EventMask)(256));
			this.buttonswidget.Name = "buttonswidget";
			this.hbox1.Add (this.buttonswidget);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonswidget]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame ();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment13 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment13.Name = "GtkAlignment13";
			this.GtkAlignment13.LeftPadding = ((uint)(12));
			// Container child GtkAlignment13.Gtk.Container+ContainerChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.fieldeventbox = new global::Gtk.EventBox ();
			this.fieldeventbox.Name = "fieldeventbox";
			// Container child fieldeventbox.Gtk.Container+ContainerChild
			this.fieldimage = new global::Gtk.Image ();
			this.fieldimage.Name = "fieldimage";
			this.fieldeventbox.Add (this.fieldimage);
			this.hbox6.Add (this.fieldeventbox);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fieldeventbox]));
			w3.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.resetfieldbutton = new global::Gtk.Button ();
			this.resetfieldbutton.CanFocus = true;
			this.resetfieldbutton.Name = "resetfieldbutton";
			this.resetfieldbutton.UseUnderline = true;
			// Container child resetfieldbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w4 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w5 = new global::Gtk.HBox ();
			w5.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
			w5.Add (w6);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w8 = new global::Gtk.Label ();
			w5.Add (w8);
			w4.Add (w5);
			this.resetfieldbutton.Add (w4);
			this.hbox6.Add (this.resetfieldbutton);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.resetfieldbutton]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.GtkAlignment13.Add (this.hbox6);
			this.frame8.Add (this.GtkAlignment13);
			this.GtkLabel17 = new global::Gtk.Label ();
			this.GtkLabel17.Name = "GtkLabel17";
			this.GtkLabel17.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Field</b>");
			this.GtkLabel17.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel17;
			this.hbox4.Add (this.frame8);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.frame8]));
			w15.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame9 = new global::Gtk.Frame ();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame9.Gtk.Container+ContainerChild
			this.GtkAlignment15 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment15.Name = "GtkAlignment15";
			this.GtkAlignment15.LeftPadding = ((uint)(12));
			// Container child GtkAlignment15.Gtk.Container+ContainerChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hfieldeventbox = new global::Gtk.EventBox ();
			this.hfieldeventbox.Name = "hfieldeventbox";
			// Container child hfieldeventbox.Gtk.Container+ContainerChild
			this.hfieldimage = new global::Gtk.Image ();
			this.hfieldimage.Name = "hfieldimage";
			this.hfieldeventbox.Add (this.hfieldimage);
			this.hbox7.Add (this.hfieldeventbox);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hfieldeventbox]));
			w17.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.resethfieldbutton = new global::Gtk.Button ();
			this.resethfieldbutton.CanFocus = true;
			this.resethfieldbutton.Name = "resethfieldbutton";
			this.resethfieldbutton.UseUnderline = true;
			// Container child resethfieldbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w18 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w19 = new global::Gtk.HBox ();
			w19.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w20 = new global::Gtk.Image ();
			w20.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
			w19.Add (w20);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w22 = new global::Gtk.Label ();
			w19.Add (w22);
			w18.Add (w19);
			this.resethfieldbutton.Add (w18);
			this.hbox7.Add (this.resethfieldbutton);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.resethfieldbutton]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.GtkAlignment15.Add (this.hbox7);
			this.frame9.Add (this.GtkAlignment15);
			this.GtkLabel20 = new global::Gtk.Label ();
			this.GtkLabel20.Name = "GtkLabel20";
			this.GtkLabel20.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Half field</b>");
			this.GtkLabel20.UseMarkup = true;
			this.frame9.LabelWidget = this.GtkLabel20;
			this.hbox4.Add (this.frame9);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.frame9]));
			w29.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.frame10 = new global::Gtk.Frame ();
			this.frame10.Name = "frame10";
			this.frame10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame10.Gtk.Container+ContainerChild
			this.GtkAlignment17 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment17.Name = "GtkAlignment17";
			this.GtkAlignment17.LeftPadding = ((uint)(12));
			// Container child GtkAlignment17.Gtk.Container+ContainerChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.goaleventbox = new global::Gtk.EventBox ();
			this.goaleventbox.Name = "goaleventbox";
			// Container child goaleventbox.Gtk.Container+ContainerChild
			this.goalimage = new global::Gtk.Image ();
			this.goalimage.Name = "goalimage";
			this.goaleventbox.Add (this.goalimage);
			this.hbox8.Add (this.goaleventbox);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.goaleventbox]));
			w31.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.resetfgoalbutton = new global::Gtk.Button ();
			this.resetfgoalbutton.CanFocus = true;
			this.resetfgoalbutton.Name = "resetfgoalbutton";
			this.resetfgoalbutton.UseUnderline = true;
			// Container child resetfgoalbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w32 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w33 = new global::Gtk.HBox ();
			w33.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w34 = new global::Gtk.Image ();
			w34.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
			w33.Add (w34);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w36 = new global::Gtk.Label ();
			w33.Add (w36);
			w32.Add (w33);
			this.resetfgoalbutton.Add (w32);
			this.hbox8.Add (this.resetfgoalbutton);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.resetfgoalbutton]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			this.GtkAlignment17.Add (this.hbox8);
			this.frame10.Add (this.GtkAlignment17);
			this.GtkLabel22 = new global::Gtk.Label ();
			this.GtkLabel22.Name = "GtkLabel22";
			this.GtkLabel22.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Goal</b>");
			this.GtkLabel22.UseMarkup = true;
			this.frame10.LabelWidget = this.GtkLabel22;
			this.hbox4.Add (this.frame10);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.frame10]));
			w43.Position = 2;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.categoryproperties = new global::LongoMatch.Gui.Component.CategoryProperties ();
			this.categoryproperties.Events = ((global::Gdk.EventMask)(256));
			this.categoryproperties.Name = "categoryproperties";
			this.vbox3.Add (this.categoryproperties);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.categoryproperties]));
			w45.Position = 1;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w47.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.savebutton = new global::Gtk.Button ();
			this.savebutton.CanFocus = true;
			this.savebutton.Name = "savebutton";
			this.savebutton.UseUnderline = true;
			// Container child savebutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w48 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w49 = new global::Gtk.HBox ();
			w49.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w50 = new global::Gtk.Image ();
			w50.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Dialog);
			w49.Add (w50);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w52 = new global::Gtk.Label ();
			w52.LabelProp = global::Mono.Unix.Catalog.GetString ("Save template");
			w52.UseUnderline = true;
			w49.Add (w52);
			w48.Add (w49);
			this.savebutton.Add (w48);
			this.hbuttonbox2.Add (this.savebutton);
			global::Gtk.ButtonBox.ButtonBoxChild w56 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.savebutton]));
			w56.Expand = false;
			w56.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.newbutton = new global::Gtk.Button ();
			this.newbutton.CanFocus = true;
			this.newbutton.Name = "newbutton";
			this.newbutton.UseUnderline = true;
			// Container child newbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w57 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w58 = new global::Gtk.HBox ();
			w58.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w59 = new global::Gtk.Image ();
			w59.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Dialog);
			w58.Add (w59);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w61 = new global::Gtk.Label ();
			w61.LabelProp = global::Mono.Unix.Catalog.GetString ("New category");
			w61.UseUnderline = true;
			w58.Add (w61);
			w57.Add (w58);
			this.newbutton.Add (w57);
			this.hbuttonbox2.Add (this.newbutton);
			global::Gtk.ButtonBox.ButtonBoxChild w65 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.newbutton]));
			w65.Position = 1;
			w65.Expand = false;
			w65.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.deletebutton = new global::Gtk.Button ();
			this.deletebutton.CanFocus = true;
			this.deletebutton.Name = "deletebutton";
			this.deletebutton.UseUnderline = true;
			// Container child deletebutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w66 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w67 = new global::Gtk.HBox ();
			w67.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w68 = new global::Gtk.Image ();
			w68.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Dialog);
			w67.Add (w68);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w70 = new global::Gtk.Label ();
			w70.LabelProp = global::Mono.Unix.Catalog.GetString ("Delete category");
			w70.UseUnderline = true;
			w67.Add (w70);
			w66.Add (w67);
			this.deletebutton.Add (w66);
			this.hbuttonbox2.Add (this.deletebutton);
			global::Gtk.ButtonBox.ButtonBoxChild w74 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.deletebutton]));
			w74.Position = 2;
			w74.Expand = false;
			w74.Fill = false;
			this.vbox2.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbuttonbox2]));
			w75.Position = 1;
			w75.Expand = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
