
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class CategoryProperties
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Table table2;
		private global::Gtk.ColorButton colorbutton1;
		private global::Gtk.ColorButton colorbutton2;
		private global::Gtk.Label label1;
		private global::Gtk.Label label13;
		private global::Gtk.Label label4;
		private global::Gtk.Label label7;
		private global::Gtk.Label label8;
		private global::Gtk.SpinButton lagtimebutton;
		private global::Gtk.SpinButton leadtimebutton;
		private global::Gtk.Entry nameentry;
		private global::Gtk.Label taglabel;
		private global::Gtk.ComboBox tagmodecombobox;
		private global::Gtk.Table cattable;
		private global::Gtk.ComboBox fieldcombobox;
		private global::Gtk.ComboBox goalcombobox;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label hotKeyLabel;
		private global::Gtk.Button changebuton;
		private global::Gtk.ComboBox hfieldcombobox;
		private global::Gtk.Label label10;
		private global::Gtk.Label label11;
		private global::Gtk.Label label12;
		private global::Gtk.Label label14;
		private global::Gtk.Label label15;
		private global::Gtk.Label label6;
		private global::Gtk.Label label9;
		private global::Gtk.ComboBox sortmethodcombobox;
		private global::Gtk.CheckButton tagscheckbutton;
		private global::Gtk.SpinButton tprbutton;
		private global::Gtk.Table cardtable;
		private global::Gtk.Label label16;
		private global::Gtk.ComboBox shapecombobox;
		private global::Gtk.Table scoretable;
		private global::Gtk.Label label17;
		private global::Gtk.SpinButton pointsbutton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.CategoryProperties
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.CategoryProperties";
			// Container child LongoMatch.Gui.Component.CategoryProperties.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), true);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.colorbutton1 = new global::Gtk.ColorButton ();
			this.colorbutton1.CanFocus = true;
			this.colorbutton1.Events = ((global::Gdk.EventMask)(784));
			this.colorbutton1.Name = "colorbutton1";
			this.table2.Add (this.colorbutton1);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.colorbutton1]));
			w1.TopAttach = ((uint)(1));
			w1.BottomAttach = ((uint)(2));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.colorbutton2 = new global::Gtk.ColorButton ();
			this.colorbutton2.CanFocus = true;
			this.colorbutton2.Events = ((global::Gdk.EventMask)(784));
			this.colorbutton2.Name = "colorbutton2";
			this.table2.Add (this.colorbutton2);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.colorbutton2]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 1F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Name</b>");
			this.label1.UseMarkup = true;
			this.table2.Add (this.label1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 1F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Text color</b>");
			this.label13.UseMarkup = true;
			this.table2.Add (this.label13);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.label13]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Color</b>");
			this.label4.UseMarkup = true;
			this.table2.Add (this.label4);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.label4]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Lead time (s)</b>");
			this.label7.UseMarkup = true;
			this.table2.Add (this.label7);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
			w6.TopAttach = ((uint)(4));
			w6.BottomAttach = ((uint)(5));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Lag time (s)</b>");
			this.label8.UseMarkup = true;
			this.table2.Add (this.label8);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.label8]));
			w7.TopAttach = ((uint)(5));
			w7.BottomAttach = ((uint)(6));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.lagtimebutton = new global::Gtk.SpinButton (0, 1000, 1);
			this.lagtimebutton.CanFocus = true;
			this.lagtimebutton.Name = "lagtimebutton";
			this.lagtimebutton.Adjustment.PageIncrement = 1;
			this.lagtimebutton.ClimbRate = 1;
			this.lagtimebutton.Numeric = true;
			this.table2.Add (this.lagtimebutton);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.lagtimebutton]));
			w8.TopAttach = ((uint)(5));
			w8.BottomAttach = ((uint)(6));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.leadtimebutton = new global::Gtk.SpinButton (0, 1000, 1);
			this.leadtimebutton.CanFocus = true;
			this.leadtimebutton.Name = "leadtimebutton";
			this.leadtimebutton.Adjustment.PageIncrement = 1;
			this.leadtimebutton.ClimbRate = 1;
			this.leadtimebutton.Numeric = true;
			this.table2.Add (this.leadtimebutton);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.leadtimebutton]));
			w9.TopAttach = ((uint)(4));
			w9.BottomAttach = ((uint)(5));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.nameentry = new global::Gtk.Entry ();
			this.nameentry.WidthRequest = 76;
			this.nameentry.CanFocus = true;
			this.nameentry.Name = "nameentry";
			this.nameentry.IsEditable = true;
			this.nameentry.InvisibleChar = '●';
			this.table2.Add (this.nameentry);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.nameentry]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.taglabel = new global::Gtk.Label ();
			this.taglabel.Name = "taglabel";
			this.taglabel.Xalign = 1F;
			this.taglabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Tag mode</b>");
			this.taglabel.UseMarkup = true;
			this.table2.Add (this.taglabel);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.taglabel]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.tagmodecombobox = global::Gtk.ComboBox.NewText ();
			this.tagmodecombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Automatic"));
			this.tagmodecombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Manual"));
			this.tagmodecombobox.Name = "tagmodecombobox";
			this.tagmodecombobox.Active = 0;
			this.table2.Add (this.tagmodecombobox);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.tagmodecombobox]));
			w12.TopAttach = ((uint)(3));
			w12.BottomAttach = ((uint)(4));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.table2);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table2]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.cattable = new global::Gtk.Table (((uint)(7)), ((uint)(2)), true);
			this.cattable.Name = "cattable";
			this.cattable.RowSpacing = ((uint)(6));
			this.cattable.ColumnSpacing = ((uint)(6));
			// Container child cattable.Gtk.Table+TableChild
			this.fieldcombobox = global::Gtk.ComboBox.NewText ();
			this.fieldcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Not tagged"));
			this.fieldcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Tag as point"));
			this.fieldcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Tag as trayectory"));
			this.fieldcombobox.Name = "fieldcombobox";
			this.fieldcombobox.Active = 0;
			this.cattable.Add (this.fieldcombobox);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.cattable [this.fieldcombobox]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.goalcombobox = global::Gtk.ComboBox.NewText ();
			this.goalcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Not tagged"));
			this.goalcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Tag as point"));
			this.goalcombobox.Name = "goalcombobox";
			this.goalcombobox.Active = 0;
			this.cattable.Add (this.goalcombobox);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.cattable [this.goalcombobox]));
			w15.TopAttach = ((uint)(6));
			w15.BottomAttach = ((uint)(7));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hotKeyLabel = new global::Gtk.Label ();
			this.hotKeyLabel.Name = "hotKeyLabel";
			this.hotKeyLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("none");
			this.hbox5.Add (this.hotKeyLabel);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hotKeyLabel]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.changebuton = new global::Gtk.Button ();
			this.changebuton.Sensitive = false;
			this.changebuton.CanFocus = true;
			this.changebuton.Name = "changebuton";
			this.changebuton.UseUnderline = true;
			this.changebuton.Label = global::Mono.Unix.Catalog.GetString ("Change");
			this.hbox5.Add (this.changebuton);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.changebuton]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.cattable.Add (this.hbox5);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.cattable [this.hbox5]));
			w18.TopAttach = ((uint)(2));
			w18.BottomAttach = ((uint)(3));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.hfieldcombobox = global::Gtk.ComboBox.NewText ();
			this.hfieldcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Not tagged"));
			this.hfieldcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Tag as point"));
			this.hfieldcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Tag as trayectory"));
			this.hfieldcombobox.Name = "hfieldcombobox";
			this.hfieldcombobox.Active = 0;
			this.cattable.Add (this.hfieldcombobox);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.cattable [this.hfieldcombobox]));
			w19.TopAttach = ((uint)(5));
			w19.BottomAttach = ((uint)(6));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Field position</b>");
			this.label10.UseMarkup = true;
			this.cattable.Add (this.label10);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.cattable [this.label10]));
			w20.TopAttach = ((uint)(4));
			w20.BottomAttach = ((uint)(5));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Half field position</b>");
			this.label11.UseMarkup = true;
			this.cattable.Add (this.label11);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.cattable [this.label11]));
			w21.TopAttach = ((uint)(5));
			w21.BottomAttach = ((uint)(6));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Goal position</b>");
			this.label12.UseMarkup = true;
			this.cattable.Add (this.label12);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.cattable [this.label12]));
			w22.TopAttach = ((uint)(6));
			w22.BottomAttach = ((uint)(7));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Show tags</b>");
			this.label14.UseMarkup = true;
			this.cattable.Add (this.label14);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.cattable [this.label14]));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xalign = 1F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Tags per row</b>");
			this.label15.UseMarkup = true;
			this.cattable.Add (this.label15);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.cattable [this.label15]));
			w24.TopAttach = ((uint)(1));
			w24.BottomAttach = ((uint)(2));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>HotKey</b>");
			this.label6.UseMarkup = true;
			this.cattable.Add (this.label6);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.cattable [this.label6]));
			w25.TopAttach = ((uint)(2));
			w25.BottomAttach = ((uint)(3));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Sort Method</b>");
			this.label9.UseMarkup = true;
			this.cattable.Add (this.label9);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.cattable [this.label9]));
			w26.TopAttach = ((uint)(3));
			w26.BottomAttach = ((uint)(4));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.sortmethodcombobox = global::Gtk.ComboBox.NewText ();
			this.sortmethodcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Sort by name"));
			this.sortmethodcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Sort by start time"));
			this.sortmethodcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Sort by stop time"));
			this.sortmethodcombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Sort by duration"));
			this.sortmethodcombobox.Name = "sortmethodcombobox";
			this.sortmethodcombobox.Active = 0;
			this.cattable.Add (this.sortmethodcombobox);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.cattable [this.sortmethodcombobox]));
			w27.TopAttach = ((uint)(3));
			w27.BottomAttach = ((uint)(4));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.tagscheckbutton = new global::Gtk.CheckButton ();
			this.tagscheckbutton.CanFocus = true;
			this.tagscheckbutton.Name = "tagscheckbutton";
			this.tagscheckbutton.Label = "";
			this.tagscheckbutton.Active = true;
			this.tagscheckbutton.DrawIndicator = true;
			this.cattable.Add (this.tagscheckbutton);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.cattable [this.tagscheckbutton]));
			w28.LeftAttach = ((uint)(1));
			w28.RightAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cattable.Gtk.Table+TableChild
			this.tprbutton = new global::Gtk.SpinButton (1, 10, 1);
			this.tprbutton.CanFocus = true;
			this.tprbutton.Name = "tprbutton";
			this.tprbutton.Adjustment.PageIncrement = 1;
			this.tprbutton.ClimbRate = 1;
			this.tprbutton.Numeric = true;
			this.tprbutton.Value = 2;
			this.cattable.Add (this.tprbutton);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.cattable [this.tprbutton]));
			w29.TopAttach = ((uint)(1));
			w29.BottomAttach = ((uint)(2));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.cattable);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.cattable]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.cardtable = new global::Gtk.Table (((uint)(1)), ((uint)(2)), true);
			this.cardtable.Name = "cardtable";
			this.cardtable.RowSpacing = ((uint)(6));
			this.cardtable.ColumnSpacing = ((uint)(6));
			// Container child cardtable.Gtk.Table+TableChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 1F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Shape</b>");
			this.label16.UseMarkup = true;
			this.cardtable.Add (this.label16);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.cardtable [this.label16]));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child cardtable.Gtk.Table+TableChild
			this.shapecombobox = global::Gtk.ComboBox.NewText ();
			this.shapecombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Rectangle"));
			this.shapecombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Triangle"));
			this.shapecombobox.AppendText (global::Mono.Unix.Catalog.GetString ("Circle"));
			this.shapecombobox.Name = "shapecombobox";
			this.shapecombobox.Active = 0;
			this.cardtable.Add (this.shapecombobox);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.cardtable [this.shapecombobox]));
			w32.LeftAttach = ((uint)(1));
			w32.RightAttach = ((uint)(2));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.cardtable);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.cardtable]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.scoretable = new global::Gtk.Table (((uint)(1)), ((uint)(2)), true);
			this.scoretable.Name = "scoretable";
			this.scoretable.RowSpacing = ((uint)(6));
			this.scoretable.ColumnSpacing = ((uint)(6));
			// Container child scoretable.Gtk.Table+TableChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.Xalign = 1F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Points</b>");
			this.label17.UseMarkup = true;
			this.scoretable.Add (this.label17);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.scoretable [this.label17]));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child scoretable.Gtk.Table+TableChild
			this.pointsbutton = new global::Gtk.SpinButton (0, 1000, 1);
			this.pointsbutton.CanFocus = true;
			this.pointsbutton.Name = "pointsbutton";
			this.pointsbutton.Adjustment.PageIncrement = 1;
			this.pointsbutton.ClimbRate = 1;
			this.pointsbutton.Numeric = true;
			this.scoretable.Add (this.pointsbutton);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.scoretable [this.pointsbutton]));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(2));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.scoretable);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.scoretable]));
			w36.Position = 3;
			w36.Expand = false;
			w36.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.cattable.Hide ();
			this.cardtable.Hide ();
			this.scoretable.Hide ();
			this.Show ();
		}
	}
}
