
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class ProjectPeriods
	{
		private global::Gtk.EventBox headereventbox;
		
		private global::Gtk.VPaned vpaned2;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox playbins_hbox;
		
		private global::LongoMatch.Gui.PlayerBin main_cam_playerbin;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Alignment labels_alignment;
		
		private global::Gtk.VBox labels_vbox;
		
		private global::Gtk.DrawingArea labelsarea;
		
		private global::Gtk.HBox zoomhbox;
		
		private global::Gtk.Image zoomoutimage;
		
		private global::Gtk.HScale zoomscale;
		
		private global::Gtk.Image zoominimage;
		
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.DrawingArea timerulearea;
		
		private global::Gtk.ScrolledWindow scrolledwindow2;
		
		private global::Gtk.DrawingArea timelinearea;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.ProjectPeriods
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.ProjectPeriods";
			// Container child LongoMatch.Gui.Component.ProjectPeriods.Gtk.Container+ContainerChild
			this.headereventbox = new global::Gtk.EventBox ();
			this.headereventbox.Name = "headereventbox";
			// Container child headereventbox.Gtk.Container+ContainerChild
			this.vpaned2 = new global::Gtk.VPaned ();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 400;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.playbins_hbox = new global::Gtk.HBox ();
			this.playbins_hbox.Name = "playbins_hbox";
			this.playbins_hbox.Homogeneous = true;
			this.playbins_hbox.Spacing = 15;
			this.playbins_hbox.BorderWidth = ((uint)(15));
			// Container child playbins_hbox.Gtk.Box+BoxChild
			this.main_cam_playerbin = new global::LongoMatch.Gui.PlayerBin ();
			this.main_cam_playerbin.Events = ((global::Gdk.EventMask)(256));
			this.main_cam_playerbin.Name = "main_cam_playerbin";
			this.main_cam_playerbin.CloseAlwaysVisible = false;
			this.playbins_hbox.Add (this.main_cam_playerbin);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.playbins_hbox [this.main_cam_playerbin]));
			w1.Position = 0;
			this.vbox2.Add (this.playbins_hbox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.playbins_hbox]));
			w2.Position = 0;
			this.vpaned2.Add (this.vbox2);
			global::Gtk.Paned.PanedChild w3 = ((global::Gtk.Paned.PanedChild)(this.vpaned2 [this.vbox2]));
			w3.Resize = false;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			// Container child hbox3.Gtk.Box+BoxChild
			this.labels_alignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.labels_alignment.Name = "labels_alignment";
			// Container child labels_alignment.Gtk.Container+ContainerChild
			this.labels_vbox = new global::Gtk.VBox ();
			this.labels_vbox.Name = "labels_vbox";
			// Container child labels_vbox.Gtk.Box+BoxChild
			this.labelsarea = new global::Gtk.DrawingArea ();
			this.labelsarea.Name = "labelsarea";
			this.labels_vbox.Add (this.labelsarea);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.labels_vbox [this.labelsarea]));
			w4.Position = 0;
			// Container child labels_vbox.Gtk.Box+BoxChild
			this.zoomhbox = new global::Gtk.HBox ();
			this.zoomhbox.Name = "zoomhbox";
			this.zoomhbox.Spacing = 6;
			// Container child zoomhbox.Gtk.Box+BoxChild
			this.zoomoutimage = new global::Gtk.Image ();
			this.zoomoutimage.WidthRequest = 14;
			this.zoomoutimage.HeightRequest = 8;
			this.zoomoutimage.Name = "zoomoutimage";
			this.zoomhbox.Add (this.zoomoutimage);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.zoomhbox [this.zoomoutimage]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child zoomhbox.Gtk.Box+BoxChild
			this.zoomscale = new global::Gtk.HScale (null);
			this.zoomscale.CanFocus = true;
			this.zoomscale.Name = "zoomscale";
			this.zoomscale.Adjustment.Upper = 100;
			this.zoomscale.Adjustment.PageIncrement = 10;
			this.zoomscale.Adjustment.StepIncrement = 1;
			this.zoomscale.DrawValue = false;
			this.zoomscale.Digits = 0;
			this.zoomscale.ValuePos = ((global::Gtk.PositionType)(2));
			this.zoomhbox.Add (this.zoomscale);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.zoomhbox [this.zoomscale]));
			w6.Position = 1;
			// Container child zoomhbox.Gtk.Box+BoxChild
			this.zoominimage = new global::Gtk.Image ();
			this.zoominimage.WidthRequest = 14;
			this.zoominimage.HeightRequest = 8;
			this.zoominimage.Name = "zoominimage";
			this.zoomhbox.Add (this.zoominimage);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.zoomhbox [this.zoominimage]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.labels_vbox.Add (this.zoomhbox);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.labels_vbox [this.zoomhbox]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.labels_alignment.Add (this.labels_vbox);
			this.hbox3.Add (this.labels_alignment);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.labels_alignment]));
			w10.Position = 0;
			w10.Expand = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			// Container child vbox7.Gtk.Box+BoxChild
			this.timerulearea = new global::Gtk.DrawingArea ();
			this.timerulearea.Name = "timerulearea";
			this.vbox7.Add (this.timerulearea);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.timerulearea]));
			w11.Position = 0;
			w11.Expand = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.HeightRequest = 50;
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.scrolledwindow2.HscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w12 = new global::Gtk.Viewport ();
			w12.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.timelinearea = new global::Gtk.DrawingArea ();
			this.timelinearea.Name = "timelinearea";
			w12.Add (this.timelinearea);
			this.scrolledwindow2.Add (w12);
			this.vbox7.Add (this.scrolledwindow2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.scrolledwindow2]));
			w15.Position = 1;
			this.hbox3.Add (this.vbox7);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox7]));
			w16.Position = 1;
			this.vpaned2.Add (this.hbox3);
			this.headereventbox.Add (this.vpaned2);
			this.Add (this.headereventbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
