
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Panel
{
	public partial class CameraSynchronizationPanel
	{
		private global::Gtk.VBox vbox3;

		private global::LongoMatch.Gui.Panel.PanelHeader panelheader1;

		private global::LongoMatch.Gui.Component.SynchronizationWidget synchronizationwidget1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Panel.CameraSynchronizationPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Panel.CameraSynchronizationPanel";
			// Container child LongoMatch.Gui.Panel.CameraSynchronizationPanel.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.panelheader1 = new global::LongoMatch.Gui.Panel.PanelHeader ();
			this.panelheader1.Events = ((global::Gdk.EventMask)(256));
			this.panelheader1.Name = "panelheader1";
			this.vbox3.Add (this.panelheader1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.panelheader1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.synchronizationwidget1 = new global::LongoMatch.Gui.Component.SynchronizationWidget ();
			this.synchronizationwidget1.Events = ((global::Gdk.EventMask)(256));
			this.synchronizationwidget1.Name = "synchronizationwidget1";
			this.vbox3.Add (this.synchronizationwidget1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.synchronizationwidget1]));
			w2.Position = 1;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
