
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class CodingWidget
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.RadioAction timelineMode;
		private global::Gtk.RadioAction autoTaggingMode;
		private global::Gtk.Action zoomFitAction;
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Toolbar codingtoolbar;
		private global::Gtk.HBox hbox2;
		private global::Gtk.DrawingArea drawingarea1;
		private global::LongoMatch.Gui.Component.ButtonsWidget buttonswidget;
		private global::LongoMatch.Gui.Component.Timeline timeline;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.CodingWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach (this);
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Default");
			this.timelineMode = new global::Gtk.RadioAction ("timelineMode", null, global::Mono.Unix.Catalog.GetString ("Timeline view"), "gtk-justify-fill", 0);
			this.timelineMode.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			w2.Add (this.timelineMode, null);
			this.autoTaggingMode = new global::Gtk.RadioAction ("autoTaggingMode", null, global::Mono.Unix.Catalog.GetString ("Automatic tagging view"), "gtk-select-color", 0);
			this.autoTaggingMode.Group = this.timelineMode.Group;
			w2.Add (this.autoTaggingMode, null);
			this.zoomFitAction = new global::Gtk.Action ("zoomFitAction", null, null, "gtk-zoom-fit");
			w2.Add (this.zoomFitAction, null);
			this.UIManager.InsertActionGroup (w2, 0);
			global::Gtk.ActionGroup w3 = new global::Gtk.ActionGroup ("Timeline");
			this.UIManager.InsertActionGroup (w3, 1);
			this.Name = "LongoMatch.Gui.Component.CodingWidget";
			// Container child LongoMatch.Gui.Component.CodingWidget.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='codingtoolbar'><toolitem name='autoTaggingMode' action='autoTaggingMode'/><toolitem name='timelineMode' action='timelineMode'/></toolbar></ui>");
			this.codingtoolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/codingtoolbar")));
			this.codingtoolbar.Name = "codingtoolbar";
			this.codingtoolbar.ShowArrow = false;
			this.hbox1.Add (this.codingtoolbar);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.codingtoolbar]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.Name = "drawingarea1";
			this.hbox2.Add (this.drawingarea1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.drawingarea1]));
			w6.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonswidget = new global::LongoMatch.Gui.Component.ButtonsWidget ();
			this.buttonswidget.Events = ((global::Gdk.EventMask)(256));
			this.buttonswidget.Name = "buttonswidget";
			this.hbox2.Add (this.buttonswidget);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.buttonswidget]));
			w7.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.timeline = new global::LongoMatch.Gui.Component.Timeline ();
			this.timeline.Events = ((global::Gdk.EventMask)(256));
			this.timeline.Name = "timeline";
			this.hbox2.Add (this.timeline);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.timeline]));
			w8.Position = 2;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w9.Position = 1;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			w1.SetUiManager (UIManager);
			this.Hide ();
		}
	}
}
