
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Panel
{
	public partial class SportsTemplatesPanel
	{
		private global::Gtk.VBox dashboardeditorvbox;

		private global::Gtk.EventBox headereventbox;

		private global::LongoMatch.Gui.Panel.PanelHeader panelheader1;

		private global::Gtk.Alignment contentalignment;

		private global::Gtk.VBox contentvbox;

		private global::Gtk.HBox dashboardeditorbuttonbar;

		private global::Gtk.Alignment templateimagealignment;

		private global::Gtk.Image templateimage;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label editdashboardslabel;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button newtemplatebutton;

		private global::Gtk.Image newtemplateimage;

		private global::Gtk.Button importtemplatebutton;

		private global::Gtk.Image importtemplateimage;

		private global::Gtk.Button savetemplatebutton;

		private global::Gtk.Image savetemplateimage;

		private global::Gtk.Button exporttemplatebutton;

		private global::Gtk.Image exporttemplateimage;

		private global::Gtk.Button deletetemplatebutton;

		private global::Gtk.Image deletetemplateimage;

		private global::Gtk.Image vseparatorimage;

		private global::Gtk.VBox vbox17;

		private global::Gtk.Label editbuttonslabel;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button addcategorybutton;

		private global::Gtk.Image addcategoryimage;

		private global::Gtk.Button addtagbutton1;

		private global::Gtk.Image addtagimage;

		private global::Gtk.Button scorebutton;

		private global::Gtk.Image scoreimage;

		private global::Gtk.Button cardbutton;

		private global::Gtk.Image cardimage;

		private global::Gtk.Button timerbutton;

		private global::Gtk.Image timerimage;

		private global::Gtk.Alignment categoryheaderimagealignment;

		private global::Gtk.Image categoryheaderimage;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox templatesvbox;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView dashboardseditortreeview;

		private global::Gtk.VBox vbox4;

		private global::LongoMatch.Gui.Component.DashboardWidget dashboardwidget;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Panel.SportsTemplatesPanel
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Panel.SportsTemplatesPanel";
			// Container child LongoMatch.Gui.Panel.SportsTemplatesPanel.Gtk.Container+ContainerChild
			this.dashboardeditorvbox = new global::Gtk.VBox ();
			this.dashboardeditorvbox.Name = "dashboardeditorvbox";
			this.dashboardeditorvbox.Spacing = 6;
			// Container child dashboardeditorvbox.Gtk.Box+BoxChild
			this.headereventbox = new global::Gtk.EventBox ();
			this.headereventbox.Name = "headereventbox";
			// Container child headereventbox.Gtk.Container+ContainerChild
			this.panelheader1 = new global::LongoMatch.Gui.Panel.PanelHeader ();
			this.panelheader1.Events = ((global::Gdk.EventMask)(256));
			this.panelheader1.Name = "panelheader1";
			this.headereventbox.Add (this.panelheader1);
			this.dashboardeditorvbox.Add (this.headereventbox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.dashboardeditorvbox [this.headereventbox]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child dashboardeditorvbox.Gtk.Box+BoxChild
			this.contentalignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.contentalignment.Name = "contentalignment";
			this.contentalignment.LeftPadding = ((uint)(12));
			this.contentalignment.RightPadding = ((uint)(12));
			// Container child contentalignment.Gtk.Container+ContainerChild
			this.contentvbox = new global::Gtk.VBox ();
			this.contentvbox.Name = "contentvbox";
			// Container child contentvbox.Gtk.Box+BoxChild
			this.dashboardeditorbuttonbar = new global::Gtk.HBox ();
			this.dashboardeditorbuttonbar.Name = "dashboardeditorbuttonbar";
			this.dashboardeditorbuttonbar.Spacing = 24;
			// Container child dashboardeditorbuttonbar.Gtk.Box+BoxChild
			this.templateimagealignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.templateimagealignment.Name = "templateimagealignment";
			this.templateimagealignment.LeftPadding = ((uint)(12));
			this.templateimagealignment.RightPadding = ((uint)(24));
			// Container child templateimagealignment.Gtk.Container+ContainerChild
			this.templateimage = new global::Gtk.Image ();
			this.templateimage.Name = "templateimage";
			this.templateimage.Yalign = 1F;
			this.templateimagealignment.Add (this.templateimage);
			this.dashboardeditorbuttonbar.Add (this.templateimagealignment);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.dashboardeditorbuttonbar [this.templateimagealignment]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child dashboardeditorbuttonbar.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 2;
			this.vbox3.BorderWidth = ((uint)(6));
			// Container child vbox3.Gtk.Box+BoxChild
			this.editdashboardslabel = new global::Gtk.Label ();
			this.editdashboardslabel.Name = "editdashboardslabel";
			this.editdashboardslabel.Xalign = 0F;
			this.editdashboardslabel.LabelProp = global::VAS.Core.Catalog.GetString ("Manage dashboards");
			this.editdashboardslabel.UseMarkup = true;
			this.vbox3.Add (this.editdashboardslabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.editdashboardslabel]));
			w5.Position = 0;
			w5.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.newtemplatebutton = new global::Gtk.Button ();
			this.newtemplatebutton.CanFocus = true;
			this.newtemplatebutton.Name = "newtemplatebutton";
			// Container child newtemplatebutton.Gtk.Container+ContainerChild
			this.newtemplateimage = new global::Gtk.Image ();
			this.newtemplateimage.Name = "newtemplateimage";
			this.newtemplateimage.Xpad = 5;
			this.newtemplateimage.Ypad = 5;
			this.newtemplatebutton.Add (this.newtemplateimage);
			this.hbox3.Add (this.newtemplatebutton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.newtemplatebutton]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.importtemplatebutton = new global::Gtk.Button ();
			this.importtemplatebutton.CanFocus = true;
			this.importtemplatebutton.Name = "importtemplatebutton";
			// Container child importtemplatebutton.Gtk.Container+ContainerChild
			this.importtemplateimage = new global::Gtk.Image ();
			this.importtemplateimage.Name = "importtemplateimage";
			this.importtemplateimage.Xpad = 5;
			this.importtemplateimage.Ypad = 5;
			this.importtemplatebutton.Add (this.importtemplateimage);
			this.hbox3.Add (this.importtemplatebutton);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.importtemplatebutton]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.savetemplatebutton = new global::Gtk.Button ();
			this.savetemplatebutton.CanFocus = true;
			this.savetemplatebutton.Name = "savetemplatebutton";
			// Container child savetemplatebutton.Gtk.Container+ContainerChild
			this.savetemplateimage = new global::Gtk.Image ();
			this.savetemplateimage.Name = "savetemplateimage";
			this.savetemplateimage.Xpad = 5;
			this.savetemplateimage.Ypad = 5;
			this.savetemplatebutton.Add (this.savetemplateimage);
			this.hbox3.Add (this.savetemplatebutton);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.savetemplatebutton]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.exporttemplatebutton = new global::Gtk.Button ();
			this.exporttemplatebutton.CanFocus = true;
			this.exporttemplatebutton.Name = "exporttemplatebutton";
			// Container child exporttemplatebutton.Gtk.Container+ContainerChild
			this.exporttemplateimage = new global::Gtk.Image ();
			this.exporttemplateimage.Name = "exporttemplateimage";
			this.exporttemplateimage.Xpad = 5;
			this.exporttemplateimage.Ypad = 5;
			this.exporttemplatebutton.Add (this.exporttemplateimage);
			this.hbox3.Add (this.exporttemplatebutton);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.exporttemplatebutton]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.deletetemplatebutton = new global::Gtk.Button ();
			this.deletetemplatebutton.CanFocus = true;
			this.deletetemplatebutton.Name = "deletetemplatebutton";
			// Container child deletetemplatebutton.Gtk.Container+ContainerChild
			this.deletetemplateimage = new global::Gtk.Image ();
			this.deletetemplateimage.Name = "deletetemplateimage";
			this.deletetemplateimage.Xpad = 5;
			this.deletetemplateimage.Ypad = 5;
			this.deletetemplatebutton.Add (this.deletetemplateimage);
			this.hbox3.Add (this.deletetemplatebutton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.deletetemplatebutton]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.dashboardeditorbuttonbar.Add (this.vbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.dashboardeditorbuttonbar [this.vbox3]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			// Container child dashboardeditorbuttonbar.Gtk.Box+BoxChild
			this.vseparatorimage = new global::Gtk.Image ();
			this.vseparatorimage.Name = "vseparatorimage";
			this.dashboardeditorbuttonbar.Add (this.vseparatorimage);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.dashboardeditorbuttonbar [this.vseparatorimage]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			// Container child dashboardeditorbuttonbar.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox ();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 2;
			this.vbox17.BorderWidth = ((uint)(6));
			// Container child vbox17.Gtk.Box+BoxChild
			this.editbuttonslabel = new global::Gtk.Label ();
			this.editbuttonslabel.Name = "editbuttonslabel";
			this.editbuttonslabel.Xalign = 0F;
			this.editbuttonslabel.LabelProp = global::VAS.Core.Catalog.GetString ("Manage dashboard buttons");
			this.editbuttonslabel.UseMarkup = true;
			this.vbox17.Add (this.editbuttonslabel);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.editbuttonslabel]));
			w19.Position = 0;
			w19.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.addcategorybutton = new global::Gtk.Button ();
			this.addcategorybutton.CanFocus = true;
			this.addcategorybutton.Name = "addcategorybutton";
			// Container child addcategorybutton.Gtk.Container+ContainerChild
			this.addcategoryimage = new global::Gtk.Image ();
			this.addcategoryimage.Name = "addcategoryimage";
			this.addcategoryimage.Xpad = 5;
			this.addcategoryimage.Ypad = 5;
			this.addcategorybutton.Add (this.addcategoryimage);
			this.hbox4.Add (this.addcategorybutton);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.addcategorybutton]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.addtagbutton1 = new global::Gtk.Button ();
			this.addtagbutton1.CanFocus = true;
			this.addtagbutton1.Name = "addtagbutton1";
			// Container child addtagbutton1.Gtk.Container+ContainerChild
			this.addtagimage = new global::Gtk.Image ();
			this.addtagimage.Name = "addtagimage";
			this.addtagimage.Xpad = 5;
			this.addtagimage.Ypad = 5;
			this.addtagbutton1.Add (this.addtagimage);
			this.hbox4.Add (this.addtagbutton1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.addtagbutton1]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.scorebutton = new global::Gtk.Button ();
			this.scorebutton.CanFocus = true;
			this.scorebutton.Name = "scorebutton";
			// Container child scorebutton.Gtk.Container+ContainerChild
			this.scoreimage = new global::Gtk.Image ();
			this.scoreimage.Name = "scoreimage";
			this.scoreimage.Xpad = 5;
			this.scoreimage.Ypad = 5;
			this.scorebutton.Add (this.scoreimage);
			this.hbox4.Add (this.scorebutton);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.scorebutton]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.cardbutton = new global::Gtk.Button ();
			this.cardbutton.CanFocus = true;
			this.cardbutton.Name = "cardbutton";
			// Container child cardbutton.Gtk.Container+ContainerChild
			this.cardimage = new global::Gtk.Image ();
			this.cardimage.Name = "cardimage";
			this.cardimage.Xpad = 5;
			this.cardimage.Ypad = 5;
			this.cardbutton.Add (this.cardimage);
			this.hbox4.Add (this.cardbutton);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.cardbutton]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.timerbutton = new global::Gtk.Button ();
			this.timerbutton.CanFocus = true;
			this.timerbutton.Name = "timerbutton";
			// Container child timerbutton.Gtk.Container+ContainerChild
			this.timerimage = new global::Gtk.Image ();
			this.timerimage.Name = "timerimage";
			this.timerimage.Xpad = 5;
			this.timerimage.Ypad = 5;
			this.timerbutton.Add (this.timerimage);
			this.hbox4.Add (this.timerbutton);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.timerbutton]));
			w29.Position = 4;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox17.Add (this.hbox4);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.hbox4]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			this.dashboardeditorbuttonbar.Add (this.vbox17);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.dashboardeditorbuttonbar [this.vbox17]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			// Container child dashboardeditorbuttonbar.Gtk.Box+BoxChild
			this.categoryheaderimagealignment = new global::Gtk.Alignment (1F, 1F, 0F, 0F);
			this.categoryheaderimagealignment.Name = "categoryheaderimagealignment";
			this.categoryheaderimagealignment.RightPadding = ((uint)(24));
			this.categoryheaderimagealignment.BottomPadding = ((uint)(14));
			// Container child categoryheaderimagealignment.Gtk.Container+ContainerChild
			this.categoryheaderimage = new global::Gtk.Image ();
			this.categoryheaderimage.Name = "categoryheaderimage";
			this.categoryheaderimage.Yalign = 1F;
			this.categoryheaderimagealignment.Add (this.categoryheaderimage);
			this.dashboardeditorbuttonbar.Add (this.categoryheaderimagealignment);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.dashboardeditorbuttonbar [this.categoryheaderimagealignment]));
			w33.Position = 4;
			this.contentvbox.Add (this.dashboardeditorbuttonbar);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.contentvbox [this.dashboardeditorbuttonbar]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child contentvbox.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 15;
			// Container child hbox1.Gtk.Box+BoxChild
			this.templatesvbox = new global::Gtk.VBox ();
			this.templatesvbox.WidthRequest = 280;
			this.templatesvbox.Name = "templatesvbox";
			this.templatesvbox.Spacing = 6;
			// Container child templatesvbox.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.dashboardseditortreeview = new global::Gtk.TreeView ();
			this.dashboardseditortreeview.CanFocus = true;
			this.dashboardseditortreeview.Name = "dashboardseditortreeview";
			this.GtkScrolledWindow1.Add (this.dashboardseditortreeview);
			this.templatesvbox.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.templatesvbox [this.GtkScrolledWindow1]));
			w36.Position = 0;
			this.hbox1.Add (this.templatesvbox);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.templatesvbox]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.dashboardwidget = new global::LongoMatch.Gui.Component.DashboardWidget ();
			this.dashboardwidget.Events = ((global::Gdk.EventMask)(256));
			this.dashboardwidget.Name = "dashboardwidget";
			this.vbox4.Add (this.dashboardwidget);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.dashboardwidget]));
			w38.Position = 0;
			this.hbox1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
			w39.Position = 1;
			this.contentvbox.Add (this.hbox1);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.contentvbox [this.hbox1]));
			w40.Position = 1;
			this.contentalignment.Add (this.contentvbox);
			this.dashboardeditorvbox.Add (this.contentalignment);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.dashboardeditorvbox [this.contentalignment]));
			w42.Position = 1;
			this.Add (this.dashboardeditorvbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
