
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui
{
	public partial class VideoWindow
	{
		private global::Gtk.EventBox videoeventbox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.VideoWindow
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.VideoWindow";
			// Container child LongoMatch.Gui.VideoWindow.Gtk.Container+ContainerChild
			this.videoeventbox = new global::Gtk.EventBox ();
			this.videoeventbox.Name = "videoeventbox";
			this.Add (this.videoeventbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
