
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Plugins.Stats
{
	public partial class CategoryViewer
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Label nodatalabel;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Frame allframe;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::LongoMatch.Gui.Component.PlaysCoordinatesTagger alltagger;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.Frame homeframe;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::LongoMatch.Gui.Component.PlaysCoordinatesTagger hometagger;
		
		private global::Gtk.Label homeLabel;
		
		private global::Gtk.Frame awayframe;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::LongoMatch.Gui.Component.PlaysCoordinatesTagger awaytagger;
		
		private global::Gtk.Label awayLabel;
		
		private global::Gtk.Label label2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Plugins.Stats.CategoryViewer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Plugins.Stats.CategoryViewer";
			// Container child LongoMatch.Plugins.Stats.CategoryViewer.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.nodatalabel = new global::Gtk.Label ();
			this.nodatalabel.Name = "nodatalabel";
			this.nodatalabel.LabelProp = global::VAS.Core.Catalog.GetString ("No data available");
			this.nodatalabel.Justify = ((global::Gtk.Justification)(2));
			this.vbox1.Add (this.nodatalabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.nodatalabel]));
			w2.Position = 0;
			this.notebook1.Add (this.vbox1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::VAS.Core.Catalog.GetString ("Statistics");
			this.notebook1.SetTabLabel (this.vbox1, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.allframe = new global::Gtk.Frame ();
			this.allframe.Name = "allframe";
			this.allframe.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child allframe.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.alltagger = new global::LongoMatch.Gui.Component.PlaysCoordinatesTagger ();
			this.alltagger.HeightRequest = 150;
			this.alltagger.Events = ((global::Gdk.EventMask)(256));
			this.alltagger.Name = "alltagger";
			this.GtkAlignment2.Add (this.alltagger);
			this.allframe.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::VAS.Core.Catalog.GetString ("<b>All</b>");
			this.GtkLabel2.UseMarkup = true;
			this.allframe.LabelWidget = this.GtkLabel2;
			this.vbox2.Add (this.allframe);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.allframe]));
			w6.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.homeframe = new global::Gtk.Frame ();
			this.homeframe.Name = "homeframe";
			this.homeframe.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child homeframe.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hometagger = new global::LongoMatch.Gui.Component.PlaysCoordinatesTagger ();
			this.hometagger.HeightRequest = 150;
			this.hometagger.Events = ((global::Gdk.EventMask)(256));
			this.hometagger.Name = "hometagger";
			this.GtkAlignment.Add (this.hometagger);
			this.homeframe.Add (this.GtkAlignment);
			this.homeLabel = new global::Gtk.Label ();
			this.homeLabel.Name = "homeLabel";
			this.homeLabel.LabelProp = global::VAS.Core.Catalog.GetString ("<b>Home</b>");
			this.homeLabel.UseMarkup = true;
			this.homeframe.LabelWidget = this.homeLabel;
			this.vbox2.Add (this.homeframe);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.homeframe]));
			w9.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.awayframe = new global::Gtk.Frame ();
			this.awayframe.Name = "awayframe";
			this.awayframe.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child awayframe.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.awaytagger = new global::LongoMatch.Gui.Component.PlaysCoordinatesTagger ();
			this.awaytagger.HeightRequest = 150;
			this.awaytagger.Events = ((global::Gdk.EventMask)(256));
			this.awaytagger.Name = "awaytagger";
			this.GtkAlignment1.Add (this.awaytagger);
			this.awayframe.Add (this.GtkAlignment1);
			this.awayLabel = new global::Gtk.Label ();
			this.awayLabel.Name = "awayLabel";
			this.awayLabel.LabelProp = global::VAS.Core.Catalog.GetString ("<b>Away</b>");
			this.awayLabel.UseMarkup = true;
			this.awayframe.LabelWidget = this.awayLabel;
			this.vbox2.Add (this.awayframe);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.awayframe]));
			w12.Position = 2;
			this.notebook1.Add (this.vbox2);
			global::Gtk.Notebook.NotebookChild w13 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox2]));
			w13.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::VAS.Core.Catalog.GetString ("Zonal tagging");
			this.notebook1.SetTabLabel (this.vbox2, this.label2);
			this.label2.ShowAll ();
			w1.Add (this.notebook1);
			this.scrolledwindow1.Add (w1);
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
