
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Plugins.Stats
{
	public partial class PlayersViewer
	{
		private global::Gtk.HPaned hpaned1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.TreeView treeview1;
		
		private global::LongoMatch.Plugins.Stats.PlayerCategoriesViewer categoriesviewer;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Plugins.Stats.PlayersViewer
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Plugins.Stats.PlayersViewer";
			// Container child LongoMatch.Plugins.Stats.PlayersViewer.Gtk.Container+ContainerChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 123;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.GtkScrolledWindow2.Add (this.treeview1);
			this.hpaned1.Add (this.GtkScrolledWindow2);
			global::Gtk.Paned.PanedChild w2 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.GtkScrolledWindow2]));
			w2.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.categoriesviewer = null;
			this.hpaned1.Add (this.categoriesviewer);
			this.Add (this.hpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
